export const playStyleOptions = [
  "Single-player",
  "Multi-player",
  "PvP",
  "Online PvP",
  "LAN PvP",
  "Shared/Split Screen PvP",
  "Co-op",
  "Online Co-op",
  "LAN Co-op",
  "Shared/Split Screen Co-op",
  "Shared/Split Screen",
  "Cross-Platform Multiplayer",
];

export const gameTypeOptions = [
  "2D",
  "Action",
  "Casual",
  "Cozy",
  "Cute",
  "Funny",
  "Open World",
  "Party",
  "Physics",
  "Platformer",
  "Puzzle",
  "Racing",
  "RPG",
  "Sandbox",
  "Sports",
];

export const filterOptions = [
  "Combat",
  "Dark Humor",
  "Dark Comedy",
  "Dating Sim",
  "Difficult",
  "Fighting",
  "Gore",
  "Hack and Slash",
  "Hentai",
  "Horror",
  "Mature",
  "NSFW",
  "Nudity",
  "Psychological",
  "Psychological Horror",
  "Shooter",
  "Sexual Content",
  "Third-Person Shooter",
  "Violent",
];
