export const playStyleOptions = [
  "Single-player",
  "Multi-player",
  "PvP",
  "Online PvP",
  "LAN PvP",
  "Shared/Split Screen PvP",
  "Co-op",
  "Online Co-op",
  "LAN Co-op",
  "Shared/Split Screen Co-op",
  "Shared/Split Screen",
  "Cross-Platform Multiplayer",
];

export const gameTypeOptions = [
  "2D",
  "Action",
  "Casual",
  "Cozy",
  "Cute",
  "Education",
  "Funny",
  "Open World",
  "Party",
  "Physics",
  "Platformer",
  "Puzzle",
  "Racing",
  "RPG",
  "Sandbox",
  "Sports",
];

export const filterOptions = [
  "Bad Language",
  "Combat",
  "Dark Humor",
  "Dark Comedy",
  "Dating Sim",
  "Difficult",
  "Fighting",
  "Gore",
  "Hack and Slash",
  "Hentai",
  "Horror",
  "Mature",
  "NSFW",
  "Nudity",
  "Action Roguelike",
  "Psychological",
  "Psychological Horror",
  "Roguelike",
  "Romance",
  "Shooter",
  "Sexual Content",
  "Third-Person Shooter",
  "Thriller",
  "Violent",
  "Wargame",
];
