// Update this list weekly with the Steam app IDs you want to feature first.
// These local fallbacks keep Popular useful if Steam pauses API access.
// Use priceLabel for a stable fallback such as "See Steam", "Free", or "$19.95".
// Platforms can be "windows", "macos", and/or "linux".
export const popularGames = [
  {
    appId: 1211020,
    name: "Wobbly Life",
    releaseDate: "Sep 18, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 433340,
    name: "Slime Rancher",
    releaseDate: "Aug 1, 2017",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 2968420,
    name: "PowerWash Simulator 2",
    releaseDate: "Oct 23, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1135690,
    name: "Unpacking",
    releaseDate: "Nov 2, 2021",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 920210,
    name: "LEGO Star Wars: The Skywalker Saga",
    releaseDate: "Apr 5, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 837470,
    name: "Untitled Goose Game",
    releaseDate: "Sep 23, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 2486820,
    name: "Sonic Racing: CrossWorlds",
    releaseDate: "Sep 25, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 431240,
    name: "Golf With Your Friends",
    releaseDate: "May 19, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 2993780,
    name: "FANTASY LIFE i: The Girl Who Steals Time",
    releaseDate: "May 21, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2495100,
    name: "Hello Kitty Island Adventure",
    releaseDate: "Jan 30, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1401590,
    name: "Disney Dreamlight Valley",
    releaseDate: "Dec 5, 2023",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1062520,
    name: "Dinkum",
    releaseDate: "Apr 22, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 728880,
    name: "Overcooked! 2",
    releaseDate: "Aug 7, 2018",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 1337010,
    name: "Alba: A Wildlife Adventure",
    releaseDate: "Dec 11, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 1586800,
    name: "Lil Gator Game",
    releaseDate: "Dec 14, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1177980,
    name: "Little Kitty, Big City",
    releaseDate: "May 9, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 284160,
    name: "BeamNG.drive",
    releaseDate: "May 29, 2015",
    priceLabel: "See Steam",
    platforms: ["windows", "linux"],
  },
];

export const popularGameAppIds = popularGames.map((game) => game.appId);

export const sharedSplitScreenCoopGames = [
  {
    appId: 1211020,
    name: "Wobbly Life",
    releaseDate: "Sep 18, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 253230,
    name: "A Hat in Time",
    releaseDate: "Oct 5, 2017",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 837470,
    name: "Untitled Goose Game",
    releaseDate: "Sep 23, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 477160,
    name: "Human Fall Flat",
    releaseDate: "Jul 22, 2016",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 584400,
    name: "Sonic Mania",
    releaseDate: "Aug 29, 2017",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2968420,
    name: "PowerWash Simulator 2",
    releaseDate: "Oct 23, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 920210,
    name: "LEGO Star Wars: The Skywalker Saga",
    releaseDate: "Apr 5, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 829110,
    name: "LEGO DC Super-Villains",
    releaseDate: "Oct 16, 2018",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 2602020,
    name: "The Smurfs - Dreams",
    releaseDate: "Nov 7, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1934870,
    name: "Wirm",
    releaseDate: "Dec 9, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
];

export const racingGames = [
  {
    appId: 284160,
    name: "BeamNG.drive",
    releaseDate: "May 29, 2015",
    priceLabel: "See Steam",
    platforms: ["windows", "linux"],
  },
  {
    appId: 2737300,
    name: "Parking Garage Rally Circuit",
    releaseDate: "Sep 20, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2486820,
    name: "Sonic Racing: CrossWorlds",
    releaseDate: "Sep 25, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1551360,
    name: "Forza Horizon 5",
    releaseDate: "Nov 8, 2021",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1205970,
    name: "MX vs ATV Legends",
    releaseDate: "Jun 28, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2581370,
    name: "Monster Energy Supercross 25 - The Official Video Game",
    releaseDate: "Apr 10, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 228380,
    name: "Wreckfest",
    releaseDate: "Jun 14, 2018",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1799930,
    name: "Redout 2",
    releaseDate: "Jun 16, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2824660,
    name: "Old School Rally",
    releaseDate: "Dec 3, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 3239650,
    name: "Garfield Kart 2 - All You Can Drift",
    releaseDate: "Sep 10, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
];
