// Update this list weekly with the Steam app IDs you want to feature first.
// These local fallbacks keep Popular useful if Steam pauses API access.
// Use priceLabel for a stable fallback such as "See Steam", "Free", or "$19.95".
// Platforms can be "windows", "macos", and/or "linux".
export const popularGames = [
  {
    appId: 1211020,
    name: "Wobbly Life",
    releaseDate: "Sep 18, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 433340,
    name: "Slime Rancher",
    releaseDate: "Aug 1, 2017",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 2968420,
    name: "PowerWash Simulator 2",
    releaseDate: "Oct 23, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1135690,
    name: "Unpacking",
    releaseDate: "Nov 2, 2021",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 920210,
    name: "LEGO Star Wars: The Skywalker Saga",
    releaseDate: "Apr 5, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 837470,
    name: "Untitled Goose Game",
    releaseDate: "Sep 23, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 2486820,
    name: "Sonic Racing: CrossWorlds",
    releaseDate: "Sep 25, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 431240,
    name: "Golf With Your Friends",
    releaseDate: "May 19, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 2993780,
    name: "FANTASY LIFE i: The Girl Who Steals Time",
    releaseDate: "May 21, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2495100,
    name: "Hello Kitty Island Adventure",
    releaseDate: "Jan 30, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1401590,
    name: "Disney Dreamlight Valley",
    releaseDate: "Dec 5, 2023",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1062520,
    name: "Dinkum",
    releaseDate: "Apr 22, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 728880,
    name: "Overcooked! 2",
    releaseDate: "Aug 7, 2018",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 1337010,
    name: "Alba: A Wildlife Adventure",
    releaseDate: "Dec 11, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 1586800,
    name: "Lil Gator Game",
    releaseDate: "Dec 14, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1177980,
    name: "Little Kitty, Big City",
    releaseDate: "May 9, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 284160,
    name: "BeamNG.drive",
    releaseDate: "May 29, 2015",
    priceLabel: "See Steam",
    platforms: ["windows", "linux"],
  },
];

export const popularGameAppIds = popularGames.map((game) => game.appId);

export const sharedSplitScreenCoopGames = [
  {
    appId: 1211020,
    name: "Wobbly Life",
    releaseDate: "Sep 18, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 253230,
    name: "A Hat in Time",
    releaseDate: "Oct 5, 2017",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 837470,
    name: "Untitled Goose Game",
    releaseDate: "Sep 23, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 477160,
    name: "Human Fall Flat",
    releaseDate: "Jul 22, 2016",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 584400,
    name: "Sonic Mania",
    releaseDate: "Aug 29, 2017",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2968420,
    name: "PowerWash Simulator 2",
    releaseDate: "Oct 23, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 920210,
    name: "LEGO Star Wars: The Skywalker Saga",
    releaseDate: "Apr 5, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 829110,
    name: "LEGO DC Super-Villains",
    releaseDate: "Oct 16, 2018",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 2602020,
    name: "The Smurfs - Dreams",
    releaseDate: "Nov 7, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1934870,
    name: "Wirm",
    releaseDate: "Dec 9, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
];

export const racingGames = [
  {
    appId: 284160,
    name: "BeamNG.drive",
    releaseDate: "May 29, 2015",
    priceLabel: "See Steam",
    platforms: ["windows", "linux"],
  },
  {
    appId: 2737300,
    name: "Parking Garage Rally Circuit",
    releaseDate: "Sep 20, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2486820,
    name: "Sonic Racing: CrossWorlds",
    releaseDate: "Sep 25, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1551360,
    name: "Forza Horizon 5",
    releaseDate: "Nov 8, 2021",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1205970,
    name: "MX vs ATV Legends",
    releaseDate: "Jun 28, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2581370,
    name: "Monster Energy Supercross 25 - The Official Video Game",
    releaseDate: "Apr 10, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 228380,
    name: "Wreckfest",
    releaseDate: "Jun 14, 2018",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1799930,
    name: "Redout 2",
    releaseDate: "Jun 16, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2824660,
    name: "Old School Rally",
    releaseDate: "Dec 3, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 3239650,
    name: "Garfield Kart 2 - All You Can Drift",
    releaseDate: "Sep 10, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2011780,
    name: "Yellow Taxi Goes Vroom",
    releaseDate: "Apr 9, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
];

export const educationGames = [
  {
    appId: 230290,
    name: "Universe Sandbox",
    releaseDate: "Aug 24, 2015",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 621060,
    name: "PC Building Simulator",
    releaseDate: "Jan 29, 2019",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 218680,
    name: "Scribblenauts Unlimited",
    releaseDate: "Nov 19, 2012",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1190000,
    name: "Car Mechanic Simulator 2021",
    releaseDate: "Aug 11, 2021",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2185060,
    name: "Two Point Museum",
    releaseDate: "Mar 4, 2025",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 883360,
    name: "Beyond Blue",
    releaseDate: "Jun 11, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 2265310,
    name: "Bug & Seek",
    releaseDate: "Dec 6, 2023",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 3531490,
    name: "Treeplanter",
    releaseDate: "Apr 21, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 2300320,
    name: "Farming Simulator 25",
    releaseDate: "Nov 12, 2024",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 1062160,
    name: "Poly Bridge 2",
    releaseDate: "May 28, 2020",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 3840230,
    name: "Adorable Adventures",
    releaseDate: "See Steam",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
];

export const legoGames = [
  {
    appId: 32440,
    name: "LEGO Star Wars - The Complete Saga",
    releaseDate: "Nov 12, 2009",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 249130,
    name: "LEGO Marvel Super Heroes",
    releaseDate: "Oct 22, 2013",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 32510,
    name: "LEGO Star Wars III - The Clone Wars",
    releaseDate: "Mar 22, 2011",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 213330,
    name: "LEGO Batman 2: DC Super Heroes",
    releaseDate: "Jun 22, 2012",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 352400,
    name: "LEGO Jurassic World",
    releaseDate: "Jun 11, 2015",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 920210,
    name: "LEGO Star Wars: The Skywalker Saga",
    releaseDate: "Apr 5, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 578330,
    name: "LEGO City Undercover",
    releaseDate: "Apr 4, 2017",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 829110,
    name: "LEGO DC Super-Villains",
    releaseDate: "Oct 16, 2018",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 311770,
    name: "LEGO Pirates of the Caribbean: The Video Game",
    releaseDate: "May 24, 2011",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 214510,
    name: "LEGO The Lord of the Rings",
    releaseDate: "Nov 27, 2012",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 21000,
    name: "LEGO Batman: The Videogame",
    releaseDate: "Sep 29, 2008",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 818320,
    name: "LEGO The Incredibles",
    releaseDate: "Jun 15, 2018",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 313690,
    name: "LEGO Batman 3: Beyond Gotham",
    releaseDate: "Nov 11, 2014",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 405310,
    name: "LEGO MARVEL's Avengers",
    releaseDate: "Jan 27, 2016",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 204120,
    name: "LEGO Harry Potter: Years 5-7",
    releaseDate: "Jan 5, 2012",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 32330,
    name: "LEGO Indiana Jones: The Original Adventures",
    releaseDate: "Jun 3, 2008",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 21130,
    name: "LEGO Harry Potter: Years 1-4",
    releaseDate: "Jun 25, 2010",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1538550,
    name: "LEGO Voyagers",
    releaseDate: "Sep 15, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 267530,
    name: "The LEGO Movie - Videogame",
    releaseDate: "Feb 7, 2014",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 647830,
    name: "LEGO Marvel Super Heroes 2",
    releaseDate: "Nov 14, 2017",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1969370,
    name: "LEGO Party!",
    releaseDate: "Sep 30, 2025",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 640590,
    name: "The LEGO NINJAGO Movie Video Game",
    releaseDate: "Sep 22, 2017",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 438640,
    name: "LEGO STAR WARS: The Force Awakens",
    releaseDate: "Jun 27, 2016",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 1544360,
    name: "LEGO Builder's Journey",
    releaseDate: "Jun 22, 2021",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1898290,
    name: "LEGO Bricktales",
    releaseDate: "Oct 12, 2022",
    priceLabel: "See Steam",
    platforms: ["windows", "macos", "linux"],
  },
  {
    appId: 32450,
    name: "LEGO Indiana Jones 2: The Adventure Continues",
    releaseDate: "Feb 18, 2010",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 285160,
    name: "LEGO The Hobbit",
    releaseDate: "Apr 8, 2014",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 2950340,
    name: "LEGO Harry Potter Collection",
    releaseDate: "Oct 8, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 332310,
    name: "LEGO Worlds",
    releaseDate: "Mar 7, 2017",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1731460,
    name: "LEGO Brawls",
    releaseDate: "Sep 2, 2022",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 1451810,
    name: "LEGO 2K Drive",
    releaseDate: "May 18, 2023",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
  {
    appId: 881320,
    name: "The LEGO Movie 2 Videogame",
    releaseDate: "Feb 26, 2019",
    priceLabel: "See Steam",
    platforms: ["windows", "macos"],
  },
  {
    appId: 2428810,
    name: "LEGO Horizon Adventures",
    releaseDate: "Nov 14, 2024",
    priceLabel: "See Steam",
    platforms: ["windows"],
  },
];
